version: "3"

services:
  rs2024:
    build: ./src/rs2024
    container_name: rs2024
    ports:
      - 80:80
      - 808:808
    volumes:
      - ./rs2024:C:/ProgramData/Autodesk/Revit Server 2024/Projects
